# Generated by Django 2.0.3 on 2018-05-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bots',
            field=models.CharField(default='[0]', max_length=200),
        ),
    ]
