# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MimicMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MimicMe
  pod 'Starscream', '~> 3.0.2'

  target 'MimicMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MimicMeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
